controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
assets:
        path: /dashboard/view/{id}
        controller: 'App\Controller\FilesController::viewFile'

